language: python
python:
    - "3.7"

env:
    -DJANGO_SETTINGS_MODULE='app.settings.dev'

install:
    - pip install -r app/requirements/dev.txt 

script:
    coverage run --source=recipes,user --include ./app manage.py test && coverage report

after_success:
    coveralls
