language: python
python:
    - "3.6"

services:
    - docker

before_script: pip install docker-compose

script: 
    - docker-compose -f dev.yml run python sh -c "coverage run manage.py test && flake8 && coverage report"

after_success:
    - docker-compose -f dev.yml run python sh -c "coverage run manage.py test && TRAVIS_JOB_ID=$TRAVIS_JOB_ID TRAVIS_BRANCH=$TRAVIS_BRANCH COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls"
