language: python
python:
    - "3.6"

services:
    - docker

before_script: pip install docker-compose

script: 
    - docker-compose -f dev.yml run python sh -c "coverage run manage.py test && flake8"
