version: "3"

services:
  python:
    build:
      context: .
      dockerfile: ./app/docker/dev/python/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"


